version: "3"

x-common: &common
    ports:
        - 5353:5353
    command: -p 5353 --enable-relay --provider

services:
    third-image:
        <<: *common
        image: erriy/third

    third-build:
        <<: *common
        build:
            context: .
            dockerfile: dockerfile