name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # mac 使用本地构建
        # todo 能否在ci中实现交叉编译
        # os: [ubuntu-20.04, windows-2019, macos-10.15]
        os: [ubuntu-20.04, windows-2019]


    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.com'

      - name: build and release application
        run: npm i && npm run build -- -p always
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
